services:
  redmine:
    image: redmine:5
    restart: always
    ports:
      - 8080:3000
    environment:
      REDMINE_DB_POSTGRES: redmine_db
      REDMINE_DB_DATABASE: redmine
      REDMINE_DB_USERNAME: redmine_user
      REDMINE_DB_PASSWORD: redmine_password
      REDMINE_DB_PORT: 5432
      REDMINE_SECRET_KEY_BASE: supersecretkey
    volumes:
      - vol_redmine:/usr/src/redmine/files
    networks:
      - internal_network
      - external_network

  redmine_db:
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: redmine
      POSTGRES_USER: redmine_user
      POSTGRES_PASSWORD: redmine_password
    networks:
      - internal_network
    volumes:
      - vol_redmine_db:/var/lib/postgresql/data

volumes:
  vol_redmine:
  vol_redmine_db:

networks:
  internal_network:
    internal: true
  external_network:
    internal: false
